version: "3.5"
services:

  joinweb:
    build:
      context: .
    command: /app/docker-compose/scripts/docker_compose_run.sh
    # Temporarily replace the command above with this if you want the container to just stay open 
    # so you can connect and troubleshoot b/c the container exits when you bring it up.
    #tty: true
    ports:
      - "3001:3001"
    # Make changes done outside the container reflect inside the container without needing a rebuild by mounting a volume.
    volumes:
      - .:/app
    networks:
      - bravendev
    depends_on:
      - joindb
    env_file:
      - docker-compose/.env-docker
    # These take precedence over any values in the above file.
    # Set them in your shell before using docker-compose so they get passed in.
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DATABASEDOTCOM_CLIENT_ID: ${DATABASEDOTCOM_CLIENT_ID}
      DATABASEDOTCOM_CLIENT_SECRET: ${DATABASEDOTCOM_CLIENT_SECRET}
      SALESFORCE_USERNAME: ${SALESFORCE_USERNAME}
      SALESFORCE_PASSWORD: ${SALESFORCE_PASSWORD}
      SALESFORCE_SECURITY_TOKEN: ${SALESFORCE_SECURITY_TOKEN}
      SALESFORCE_MAGIC_TOKEN: ${SALESFORCE_MAGIC_TOKEN}

  joindb:
    image: postgres:10.14
    networks:
      - bravendev
    volumes:
      - ./latest.dump:/latest.dump
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

# Note all Braven web app docker dev envs use this same network so they can talk to each other.
# E.g. the hostname joinweb will resolve inside the ssoweb container if they are on the same docker network.
networks:
  bravendev:
    name: braven_dev_network

volumes:
  db-data:
